### ISSUE TITLE
Jekyll-pig is lowering the gamma of the images for some reason

### ISSUE THREAD

**Issue by DuendeInexistente** [clnhlzmn/jekyll-pig#4]
![image](https://github.com/user-attachments/assets/e2751954-6169-457b-acd4-4870a1fb476a)

I wouldn't know what's wrong, as my only plugins are -pig and -loading-lazy and this is otherwise a fresh install, only with a custom post layout.

**Comment by clnhlzmn** [comment]
Hmm I think I have experienced this before but I never looked into it. Can you attach a sample image?

**Comment by DuendeInexistente** [comment]
![07 07 2](https://github.com/user-attachments/assets/44455553-1e28-45e6-b271-c387c010fac7)

![07 07 2](https://github.com/user-attachments/assets/d1cd2c2e-d0b9-4646-9dbd-35275ecc62e4)

**Comment by clnhlzmn** [comment]
I think I found the problem. Can you try again with jekyll-pig 0.0.5?

**Comment by DuendeInexistente** [comment]
Nice! That fixed it.
